# Configuration de l'outil de migration LDAP/IMAP
#
# Date : 2009-01-13
#
# Copyright (C) 2009 Farzad FARID <ffarid@pragmatic-source.com>

hostname: new-srv
ldap:
  user: cn=admin, o=customer, c=fr
  password: XXXXXXXX
  infile: customer-orig.ldif
  outfile: customer-clean.ldif
imap:
  user: cyrus
  password: YYYYY
