# Configuration de l'outil de migration LDAP/IMAP
#
# Date : 2009-01-13
#
# Copyright (C) 2009 Farzad FARID <ffarid@pragmatic-source.com>

hostname: berumail
ldap:
  user: cn=admin, o=idm, c=fr
  password: Ur,ec1blC
  infile: idm-orig.ldif
  outfile: idm-clean.ldif
imap:
  user: cyrus
  password: p0rtug4L
